"""updated_message_statuses

Revision ID: 04186a4008c4
Revises: 4970e92a8682
Create Date: 2026-05-14 13:21:13.057872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04186a4008c4'
down_revision: Union[str, Sequence[str], None] = '4970e92a8682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('created', 'queued', 'submitted', 'sending', 'delivered', 'undelivered', 'failed', 'unknown', name='messagestatus', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'status',
               existing_type=sa.Enum('created', 'queued', 'submitted', 'sending', 'delivered', 'undelivered', 'failed', 'unknown', name='messagestatus', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    # ### end Alembic commands ###
