"""Initial

Revision ID: 1209a6c16610
Revises: 
Create Date: 2026-06-29 10:53:53.182783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1209a6c16610'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('mailing.send', name='outboxeventtype', native_enum=False), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'published', 'failed', name='outboxstatus', native_enum=False), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_pending_created_at', 'outbox', ['created_at'], unique=False, postgresql_where="status = 'pending'")
    op.create_index('ix_outbox_status_next_retry_at', 'outbox', ['status', 'next_retry_at'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('api_key_hash', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_hash'),
    sa.UniqueConstraint('email')
    )
    op.create_table('mailing',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('created', 'queued', 'submitted', name='mailingstatus', native_enum=False), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages_batch',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mailing_id', sa.Uuid(), nullable=False),
    sa.Column('provider_code', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('created', 'queued', 'sending', 'submitted', 'partially_submitted', 'completed', 'partially_failed', 'failed', name='messagesbatchstatus', native_enum=False), nullable=False),
    sa.Column('messages_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mailing_id'], ['mailing.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mailing_id', sa.Uuid(), nullable=False),
    sa.Column('msisdn', sa.String(length=15), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('send_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('created', 'queued', 'submitted', 'delivered', 'undelivered', 'failed', 'unknown', name='messagestatus', native_enum=False), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['messages_batch.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mailing_id'], ['mailing.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('messages_batch')
    op.drop_table('mailing')
    op.drop_table('user')
    op.drop_index('ix_outbox_status_next_retry_at', table_name='outbox')
    op.drop_index('ix_outbox_pending_created_at', table_name='outbox', postgresql_where="status = 'pending'")
    op.drop_table('outbox')
    # ### end Alembic commands ###
