"""add_batches

Revision ID: 2534495eb229
Revises: 04186a4008c4
Create Date: 2026-05-15 11:51:17.402172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2534495eb229'
down_revision: Union[str, Sequence[str], None] = '04186a4008c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_batch',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mailing_id', sa.Uuid(), nullable=False),
    sa.Column('provider_code', sa.String(length=100), nullable=False),
    sa.Column('messages_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mailing_id'], ['mailing.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('mailing', sa.Column('provider_code', sa.String(length=100), nullable=False))
    op.add_column('message', sa.Column('batch_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'message', 'message_batch', ['batch_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'batch_id')
    op.drop_column('mailing', 'provider_code')
    op.drop_table('message_batch')
    # ### end Alembic commands ###
