"""outbox

Revision ID: 3347d0426846
Revises: 65f63cae0bde
Create Date: 2026-05-24 20:27:48.510831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3347d0426846'
down_revision: Union[str, Sequence[str], None] = '65f63cae0bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailing_outbox',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('mailing.send', name='mailingoutboxeventtype', native_enum=False), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'published', 'failed', name='mailingoutboxstatus', native_enum=False), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mailing_outbox_pending_created_at', 'mailing_outbox', ['created_at'], unique=False, postgresql_where="status = 'pending'")
    op.create_index('ix_mailing_outbox_status_next_retry_at', 'mailing_outbox', ['status', 'next_retry_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mailing_outbox_status_next_retry_at', table_name='mailing_outbox')
    op.drop_index('ix_mailing_outbox_pending_created_at', table_name='mailing_outbox', postgresql_where="status = 'pending'")
    op.drop_table('mailing_outbox')
    # ### end Alembic commands ###
