"""add_send_on_datetime_message

Revision ID: 3b584b0f4145
Revises: b86d14769d68
Create Date: 2026-05-18 09:29:35.788481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b584b0f4145'
down_revision: Union[str, Sequence[str], None] = 'b86d14769d68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'message',
        sa.Column('send_on', sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'send_on')
    # ### end Alembic commands ###
