"""statuses_update

Revision ID: 65f63cae0bde
Revises: 3b584b0f4145
Create Date: 2026-05-18 14:26:23.527855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65f63cae0bde'
down_revision: Union[str, Sequence[str], None] = '3b584b0f4145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mailing', 'status',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('created', 'prepared', 'queued', 'submitted', name='mailingstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('message', 'send_on',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'send_on',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('mailing', 'status',
               existing_type=sa.Enum('created', 'prepared', 'queued', 'submitted', name='mailingstatus', native_enum=False),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    # ### end Alembic commands ###
