"""add_api_key_to_user

Revision ID: ab906e794cc2
Revises: 43d4ca16eab3
Create Date: 2026-05-13 13:55:42.231319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab906e794cc2'
down_revision: Union[str, Sequence[str], None] = '43d4ca16eab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('api_key_hash', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'user', ['api_key_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'api_key_hash')
    # ### end Alembic commands ###
