"""add_partial_submitted_status_for_batches

Revision ID: b86d14769d68
Revises: c416052953c8
Create Date: 2026-05-18 09:08:06.385067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b86d14769d68'
down_revision: Union[str, Sequence[str], None] = 'c416052953c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages_batch', 'status',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('created', 'queued', 'sent', 'partially_submitted', 'completed', 'partially_failed', 'failed', name='messagesbatchstatus', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages_batch', 'status',
               existing_type=sa.Enum('created', 'queued', 'sent', 'partially_submitted', 'completed', 'partially_failed', 'failed', name='messagesbatchstatus', native_enum=False),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    # ### end Alembic commands ###
