"""add_external_id_to_messsages_and_batches

Revision ID: c416052953c8
Revises: 22fc26656ec8
Create Date: 2026-05-18 08:34:58.367320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c416052953c8'
down_revision: Union[str, Sequence[str], None] = '22fc26656ec8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.add_column('messages_batch', sa.Column('external_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages_batch', 'external_id')
    op.drop_column('message', 'external_id')
    # ### end Alembic commands ###
